### ISSUE TITLE
Clean up and update the Travis CI build configuration

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/inloop#274]
- Migrate to newer dist (currently still at ubuntu 14.04 aka trusty)
- Add current Python versions
- Build config must not have warnings (see screenshot below)
- Get rid of duplication

![Bildschirmfoto 2020-02-10 um 15 23 02](https://user-images.githubusercontent.com/1561982/74157831-3f699980-4c19-11ea-9677-19f3c9908505.png)

**Comment by PhilippMatthes** [comment]
@martinmo just as a side note, the following will not work:
```
matrix:
  include:
    - language: python
      name: "All Python checks"
      python:
        - "3.4"
        - "3.5"
        - "3.6"
      ...
```
This will only execute Python 3.4 tests as of my experiences.
